-- Approval Engine Tables

-- wh_approval_instance 审批实例表
CREATE TABLE IF NOT EXISTS wh_approval_instance (
    ID TEXT NOT NULL,
    BIZ_ID TEXT NOT NULL,
    FLOW_CODE TEXT NOT NULL,
    PROCESS_INSTANCE_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'RUNNING',
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    CONSTRAINT PK_WH_APPROVAL_INSTANCE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_WAI_BIZ ON wh_approval_instance(BIZ_ID);
CREATE INDEX IF NOT EXISTS IDX_WAI_PROCESS ON wh_approval_instance(PROCESS_INSTANCE_ID);

-- wh_approval_record 审批记录表
CREATE TABLE IF NOT EXISTS wh_approval_record (
    ID TEXT NOT NULL,
    INSTANCE_ID TEXT NOT NULL,
    APPROVER TEXT,
    ACTION TEXT NOT NULL,
    COMMENT TEXT,
    APPROVE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    CONSTRAINT PK_WH_APPROVAL_RECORD PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_WAR_INSTANCE ON wh_approval_record(INSTANCE_ID);
