-- Project Charter Table (FR-PM-001)
CREATE TABLE IF NOT EXISTS wh_pm_project_charter (
    ID TEXT NOT NULL,
    CHARTER_CODE TEXT NOT NULL UNIQUE,
    PROJECT_NAME TEXT NOT NULL,
    PROJECT_CODE TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    OBJECTIVES TEXT,
    SCOPE_SUMMARY TEXT,
    SPONSOR_ID TEXT NOT NULL,
    PM_ID TEXT NOT NULL,
    BUDGET_CAP TEXT,
    START_DATE TEXT,
    END_DATE TEXT,
    KEY_STAKEHOLDERS TEXT,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    APPROVAL_COMMENT TEXT,
    PROCESS_INSTANCE_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_PM_CHARTER PRIMARY KEY (ID),
    CONSTRAINT CK_WH_PM_CHARTER_STATUS CHECK (STATUS IN (
        'DRAFT','PENDING_APPROVAL','APPROVED','REJECTED','CLOSED'
    ))
);

CREATE INDEX IF NOT EXISTS IDX_WH_PM_CHARTER_STATUS ON wh_pm_project_charter(STATUS);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_CHARTER_PM ON wh_pm_project_charter(PM_ID);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_CHARTER_SPONSOR ON wh_pm_project_charter(SPONSOR_ID);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_CHARTER_DEL ON wh_pm_project_charter(DEL_FLAG);
