-- Integration Management Tables (FR-PM-002 ~ FR-PM-006)

-- pm_management_plan 项目管理计划
CREATE TABLE IF NOT EXISTS pm_management_plan (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    PLAN_VERSION TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    SCOPE_PLAN TEXT,
    SCHEDULE_PLAN TEXT,
    COST_PLAN TEXT,
    QUALITY_PLAN TEXT,
    RESOURCE_PLAN TEXT,
    COMM_PLAN TEXT,
    RISK_PLAN TEXT,
    PROCUREMENT_PLAN TEXT,
    STAKEHOLDER_PLAN TEXT,
    CHANGE_HISTORY TEXT,
    BASELINE_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_MANAGEMENT_PLAN PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_PLAN_PROJECT ON pm_management_plan(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_PM_PLAN_STATUS ON pm_management_plan(STATUS);

-- pm_plan_baseline 计划基线
CREATE TABLE IF NOT EXISTS pm_plan_baseline (
    ID TEXT NOT NULL,
    PLAN_ID TEXT NOT NULL,
    BASELINE_DATE TEXT NOT NULL,
    BASELINE_DATA TEXT NOT NULL,
    BASELINE_LABEL TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_PLAN_BASELINE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_BASELINE_PLAN ON pm_plan_baseline(PLAN_ID);

-- pm_work_log 工作日志
CREATE TABLE IF NOT EXISTS pm_work_log (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    TASK_ID TEXT,
    LOG_DATE TEXT NOT NULL,
    WORK_DESCRIPTION TEXT NOT NULL,
    HOURS_WORKED TEXT,
    STATUS TEXT NOT NULL,
    BLOCKER_REASON TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_WORK_LOG PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_WORKLOG_PROJECT ON pm_work_log(PROJECT_ID);

-- pm_issue_log 问题日志
CREATE TABLE IF NOT EXISTS pm_issue_log (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ISSUE_CODE TEXT NOT NULL UNIQUE,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT,
    SEVERITY TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    ASSIGNEE_ID TEXT,
    RESOLUTION TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_ISSUE_LOG PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_ISSUE_PROJECT ON pm_issue_log(PROJECT_ID);

-- pm_knowledge_base 知识库
CREATE TABLE IF NOT EXISTS pm_knowledge_base (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    KB_TYPE TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    CONTENT TEXT,
    FILE_PATH TEXT,
    TAGS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_KNOWLEDGE_BASE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_KB_PROJECT ON pm_knowledge_base(PROJECT_ID);

-- pm_change_request 变更请求
CREATE TABLE IF NOT EXISTS pm_change_request (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    CHANGE_CODE TEXT NOT NULL UNIQUE,
    CHANGE_TYPE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    REASON TEXT NOT NULL,
    IMPACT_ANALYSIS TEXT,
    AFFECTED_BASELINES TEXT,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    CCB_MEMBERS TEXT,
    APPROVAL_COMMENT TEXT,
    PROCESS_INSTANCE_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_CHANGE_REQUEST PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CHANGE_PROJECT ON pm_change_request(PROJECT_ID);

-- pm_project_closure 项目收尾
CREATE TABLE IF NOT EXISTS pm_project_closure (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    CLOSURE_TYPE TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'INITIATED',
    DELIVERABLE_SUMMARY TEXT,
    LESSONS_LEARNED TEXT,
    FINAL_METRICS TEXT,
    ACCEPTANCE_DATE TEXT,
    ACCEPTANCE_COMMENT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_PROJECT_CLOSURE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CLOSURE_PROJECT ON pm_project_closure(PROJECT_ID);
