-- Scope Management Tables (FR-PM-008 ~ FR-PM-012)

-- pm_requirement 需求
CREATE TABLE IF NOT EXISTS pm_requirement (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    REQ_CODE TEXT NOT NULL UNIQUE,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SOURCE TEXT,
    PRIORITY TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
    ACCEPTANCE_CRITERIA TEXT,
    WBS_ELEMENT_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_REQUIREMENT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_REQ_PROJECT ON pm_requirement(PROJECT_ID);

-- pm_rtm 需求跟踪矩阵
CREATE TABLE IF NOT EXISTS pm_rtm (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    REQ_ID TEXT NOT NULL,
    WBS_ID TEXT,
    DESIGN_DOC_ID TEXT,
    TEST_CASE_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'MAPPED',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RTM PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RTM_PROJECT ON pm_rtm(PROJECT_ID);

-- pm_scope_statement 范围说明书
CREATE TABLE IF NOT EXISTS pm_scope_statement (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    VERSION TEXT NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    ACCEPTANCE_CRITERIA TEXT,
    DELIVERABLES TEXT NOT NULL,
    EXCLUSIONS TEXT,
    CONSTRAINTS TEXT,
    ASSUMPTIONS TEXT,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SCOPE_STATEMENT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SCOPE_PROJECT ON pm_scope_statement(PROJECT_ID);

-- pm_wbs_element WBS元素
CREATE TABLE IF NOT EXISTS pm_wbs_element (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    WBS_CODE TEXT NOT NULL,
    PARENT_ID TEXT,
    LEVEL INTEGER NOT NULL,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    ELEMENT_TYPE TEXT NOT NULL,
    EFFORT_ESTIMATE TEXT,
    BUDGET_ESTIMATE TEXT,
    OWNER_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'PLANNED',
    SORT_ORDER INTEGER DEFAULT 0,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_WBS_ELEMENT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_WBS_PROJECT ON pm_wbs_element(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_PM_WBS_PARENT ON pm_wbs_element(PARENT_ID);

-- pm_scope_verification 范围确认
CREATE TABLE IF NOT EXISTS pm_scope_verification (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    DELIVERABLE_ID TEXT,
    VERIFIER_ID TEXT NOT NULL,
    VERIFICATION_DATE TEXT,
    RESULT TEXT NOT NULL,
    COMMENTS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SCOPE_VERIFICATION PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SV_PROJECT ON pm_scope_verification(PROJECT_ID);

-- pm_scope_variance 范围偏差
CREATE TABLE IF NOT EXISTS pm_scope_variance (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    BASELINE_WBS_SNAPSHOT TEXT,
    CURRENT_WBS_SNAPSHOT TEXT,
    VARIANCE_DESCRIPTION TEXT,
    VARIANCE_TYPE TEXT NOT NULL,
    IMPACT_ASSESSMENT TEXT,
    DETECTED_DATE TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SCOPE_VARIANCE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SVAR_PROJECT ON pm_scope_variance(PROJECT_ID);
