-- Schedule Management Tables (FR-PM-014 ~ FR-PM-018)

-- pm_activity 活动
CREATE TABLE IF NOT EXISTS pm_activity (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    WBS_ID TEXT,
    ACTIVITY_CODE TEXT NOT NULL UNIQUE,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    ACTIVITY_TYPE TEXT NOT NULL,
    DURATION INTEGER,
    EFFORT TEXT,
    ASSIGNEE_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'NOT_STARTED',
    ACTUAL_START TEXT,
    ACTUAL_END TEXT,
    PLANNED_START TEXT,
    PLANNED_END TEXT,
    PERCENT_COMPLETE TEXT DEFAULT '0',
    MILESTONE_FLAG TEXT DEFAULT '0',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_ACTIVITY PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_ACT_PROJECT ON pm_activity(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_PM_ACT_STATUS ON pm_activity(STATUS);

-- pm_activity_dependency 活动依赖
CREATE TABLE IF NOT EXISTS pm_activity_dependency (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    PREDECESSOR_ID TEXT NOT NULL,
    SUCCESSOR_ID TEXT NOT NULL,
    DEPENDENCY_TYPE TEXT NOT NULL,
    LAG_DAYS INTEGER DEFAULT 0,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_ACTIVITY_DEP PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_DEP_PROJECT ON pm_activity_dependency(PROJECT_ID);

-- pm_critical_path 关键路径
CREATE TABLE IF NOT EXISTS pm_critical_path (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    CALCULATED_AT TEXT NOT NULL,
    TOTAL_DURATION INTEGER NOT NULL,
    ACTIVITY_IDS TEXT NOT NULL,
    SNAPSHOT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_CRITICAL_PATH PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CP_PROJECT ON pm_critical_path(PROJECT_ID);

-- pm_activity_estimation 活动估算
CREATE TABLE IF NOT EXISTS pm_activity_estimation (
    ID TEXT NOT NULL,
    ACTIVITY_ID TEXT NOT NULL,
    METHOD TEXT NOT NULL,
    OPTIMISTIC_DAYS TEXT,
    MOST_LIKELY_DAYS TEXT,
    PESSIMISTIC_DAYS TEXT,
    PERT_DAYS TEXT,
    PERT_STD_DEV TEXT,
    SINGLE_POINT_DAYS TEXT,
    CONFIDENCE_LEVEL TEXT,
    BASIS_OF_ESTIMATE TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_ACT_EST PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_AE_ACTIVITY ON pm_activity_estimation(ACTIVITY_ID);

-- pm_schedule_variance 进度偏差
CREATE TABLE IF NOT EXISTS pm_schedule_variance (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ANALYSIS_DATE TEXT NOT NULL,
    PV TEXT,
    EV TEXT,
    SV TEXT,
    SPI TEXT,
    VARIANCE_DAYS INTEGER,
    FORECAST_END_DATE TEXT,
    ALERT_TRIGGERED TEXT DEFAULT '0',
    ANALYSIS_NOTES TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SCHED_VAR PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SV2_PROJECT ON pm_schedule_variance(PROJECT_ID);

-- pm_schedule_alert 进度预警
CREATE TABLE IF NOT EXISTS pm_schedule_alert (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ALERT_TYPE TEXT NOT NULL,
    SEVERITY TEXT NOT NULL,
    MESSAGE TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'UNREAD',
    NOTIFY_USERS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SCHED_ALERT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SA_PROJECT ON pm_schedule_alert(PROJECT_ID);
