-- Cost Management Tables (FR-PM-020 ~ FR-PM-022)

-- pm_cost_estimate 成本估算
CREATE TABLE IF NOT EXISTS pm_cost_estimate (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    WBS_ID TEXT,
    ACTIVITY_ID TEXT,
    ESTIMATE_TYPE TEXT NOT NULL,
    LABOR_COST TEXT DEFAULT '0',
    MATERIAL_COST TEXT DEFAULT '0',
    EQUIPMENT_COST TEXT DEFAULT '0',
    OTHER_COST TEXT DEFAULT '0',
    CONTINGENCY_RESERVE TEXT DEFAULT '0',
    TOTAL_ESTIMATE TEXT NOT NULL,
    CONFIDENCE_LEVEL TEXT,
    BASIS_OF_ESTIMATE TEXT,
    VERSION TEXT NOT NULL DEFAULT 'v1.0',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_COST_ESTIMATE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CE_PROJECT ON pm_cost_estimate(PROJECT_ID);

-- pm_budget 预算
CREATE TABLE IF NOT EXISTS pm_budget (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    BUDGET_CODE TEXT NOT NULL UNIQUE,
    VERSION TEXT NOT NULL,
    COST_BASELINE TEXT NOT NULL,
    MANAGEMENT_RESERVE TEXT DEFAULT '0',
    TOTAL_BUDGET TEXT NOT NULL,
    TIME_PHASED_DATA TEXT,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    APPROVAL_COMMENT TEXT,
    PROCESS_INSTANCE_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_BUDGET PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_BUDGET_PROJECT ON pm_budget(PROJECT_ID);

-- pm_actual_cost 实际成本
CREATE TABLE IF NOT EXISTS pm_actual_cost (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ACTIVITY_ID TEXT,
    COST_DATE TEXT NOT NULL,
    COST_TYPE TEXT NOT NULL,
    AMOUNT TEXT NOT NULL,
    DESCRIPTION TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_ACTUAL_COST PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_AC_PROJECT ON pm_actual_cost(PROJECT_ID);

-- pm_evm_analysis 挣值分析
CREATE TABLE IF NOT EXISTS pm_evm_analysis (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ANALYSIS_DATE TEXT NOT NULL,
    BAC TEXT,
    PV TEXT,
    EV TEXT,
    AC TEXT,
    CV TEXT,
    SV TEXT,
    CPI TEXT,
    SPI TEXT,
    EAC TEXT,
    ETC TEXT,
    VAC TEXT,
    TCPI TEXT,
    ALERT_TRIGGERED TEXT DEFAULT '0',
    ANALYSIS_NOTES TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_EVM_ANALYSIS PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_EVM_PROJECT ON pm_evm_analysis(PROJECT_ID);
