-- Quality Management Tables (FR-PM-024 ~ FR-PM-025)

-- pm_quality_audit 质量审计
CREATE TABLE IF NOT EXISTS pm_quality_audit (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    AUDIT_CODE TEXT NOT NULL UNIQUE,
    AUDIT_TYPE TEXT NOT NULL,
    AUDIT_DATE TEXT NOT NULL,
    AUDITOR_ID TEXT NOT NULL,
    SCOPE TEXT NOT NULL,
    FINDINGS TEXT,
    OVERALL_RESULT TEXT NOT NULL,
    CORRECTIVE_ACTIONS TEXT,
    STATUS TEXT NOT NULL DEFAULT 'PLANNED',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_QUALITY_AUDIT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_QA_PROJECT ON pm_quality_audit(PROJECT_ID);

-- pm_quality_defect 质量缺陷
CREATE TABLE IF NOT EXISTS pm_quality_defect (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    DEFECT_CODE TEXT NOT NULL UNIQUE,
    TITLE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    SEVERITY TEXT NOT NULL,
    PRIORITY TEXT NOT NULL,
    SOURCE TEXT NOT NULL,
    RELATED_ACTIVITY_ID TEXT,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    REPORTED_BY TEXT NOT NULL,
    ASSIGNED_TO TEXT,
    FIX_DESCRIPTION TEXT,
    FIXED_DATE TEXT,
    VERIFIED_DATE TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_QUALITY_DEFECT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_QD_PROJECT ON pm_quality_defect(PROJECT_ID);
