-- Resource Management Tables (FR-PM-027 ~ FR-PM-031)

-- pm_resource_estimate 资源估算
CREATE TABLE IF NOT EXISTS pm_resource_estimate (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ACTIVITY_ID TEXT,
    RESOURCE_TYPE TEXT NOT NULL,
    RESOURCE_ROLE TEXT,
    QUANTITY TEXT NOT NULL,
    UNIT TEXT NOT NULL,
    UNIT_COST TEXT,
    TOTAL_COST TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RESOURCE_ESTIMATE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RE_PROJECT ON pm_resource_estimate(PROJECT_ID);

-- pm_resource_assignment 资源分配
CREATE TABLE IF NOT EXISTS pm_resource_assignment (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ACTIVITY_ID TEXT,
    ASSIGNEE_ID TEXT NOT NULL,
    ROLE_IN_PROJECT TEXT NOT NULL,
    ALLOCATION_PCT TEXT NOT NULL,
    START_DATE TEXT NOT NULL,
    END_DATE TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
    NOTES TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RESOURCE_ASSIGN PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RA_PROJECT ON pm_resource_assignment(PROJECT_ID);

-- pm_resource_calendar 资源日历
CREATE TABLE IF NOT EXISTS pm_resource_calendar (
    ID TEXT NOT NULL,
    ASSIGNEE_ID TEXT NOT NULL,
    LEAVE_DATE TEXT NOT NULL,
    LEAVE_TYPE TEXT NOT NULL,
    PROJECT_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RESOURCE_CAL PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RC_ASSIGNEE ON pm_resource_calendar(ASSIGNEE_ID);

-- pm_team_skill 团队技能
CREATE TABLE IF NOT EXISTS pm_team_skill (
    ID TEXT NOT NULL,
    ASSIGNEE_ID TEXT NOT NULL,
    SKILL_NAME TEXT NOT NULL,
    PROFICIENCY INTEGER NOT NULL,
    LAST_ASSESSED TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_TEAM_SKILL PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_TS_ASSIGNEE ON pm_team_skill(ASSIGNEE_ID);

-- pm_training_record 培训记录
CREATE TABLE IF NOT EXISTS pm_training_record (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ASSIGNEE_ID TEXT NOT NULL,
    TRAINING_NAME TEXT NOT NULL,
    TRAINING_DATE TEXT,
    HOURS TEXT,
    COST TEXT,
    OUTCOME TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_TRAINING PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_TR_PROJECT ON pm_training_record(PROJECT_ID);

-- pm_resource_utilization 资源利用率
CREATE TABLE IF NOT EXISTS pm_resource_utilization (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ASSIGNEE_ID TEXT NOT NULL,
    PERIOD_START TEXT NOT NULL,
    PERIOD_END TEXT NOT NULL,
    PLANNED_HOURS TEXT,
    ACTUAL_HOURS TEXT,
    UTILIZATION_PCT TEXT,
    IDLE_HOURS TEXT,
    OVERTIME_HOURS TEXT,
    NOTES TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RES_UTIL PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RU_PROJECT ON pm_resource_utilization(PROJECT_ID);
