-- Communication Management Tables (FR-PM-033 ~ FR-PM-034)

-- pm_communication_log 沟通记录
CREATE TABLE IF NOT EXISTS pm_communication_log (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    COMM_TYPE TEXT NOT NULL,
    SUBJECT TEXT NOT NULL,
    DESCRIPTION TEXT,
    COMM_DATE TEXT NOT NULL,
    PARTICIPANTS TEXT,
    CHANNEL TEXT,
    ATTACHMENTS TEXT,
    ACTION_ITEMS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_COMM_LOG PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CL_PROJECT ON pm_communication_log(PROJECT_ID);

-- pm_meeting 会议
CREATE TABLE IF NOT EXISTS pm_meeting (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    MEETING_TYPE TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    MEETING_DATE TEXT NOT NULL,
    START_TIME TEXT,
    END_TIME TEXT,
    AGENDA TEXT,
    MINUTES TEXT,
    ACTION_ITEMS TEXT,
    ATTENDEES TEXT,
    STATUS TEXT NOT NULL DEFAULT 'SCHEDULED',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_MEETING PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_MTG_PROJECT ON pm_meeting(PROJECT_ID);

-- pm_report 报告
CREATE TABLE IF NOT EXISTS pm_report (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    REPORT_TYPE TEXT NOT NULL,
    PERIOD_START TEXT,
    PERIOD_END TEXT,
    CONTENT TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    RECIPIENTS TEXT,
    GENERATED_AT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_REPORT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RPT_PROJECT ON pm_report(PROJECT_ID);

-- pm_comm_effectiveness 沟通效果
CREATE TABLE IF NOT EXISTS pm_comm_effectiveness (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    EVALUATION_PERIOD TEXT NOT NULL,
    MEETING_ATTENDANCE_RATE TEXT,
    REPORT_TIMELINESS_PCT TEXT,
    ACTION_ITEM_COMPLETION_RATE TEXT,
    STAKEHOLDER_SATISFACTION TEXT,
    IMPROVEMENT_SUGGESTIONS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_COMM_EFF PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_CE2_PROJECT ON pm_comm_effectiveness(PROJECT_ID);
