-- Risk Management Tables (FR-PM-036 ~ FR-PM-041)

-- pm_risk_register 风险登记册
CREATE TABLE IF NOT EXISTS pm_risk_register (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    RISK_CODE TEXT NOT NULL UNIQUE,
    CATEGORY TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    CAUSE TEXT,
    TRIGGER_CONDITION TEXT,
    PROBABILITY INTEGER,
    IMPACT INTEGER,
    RISK_SCORE INTEGER,
    RISK_LEVEL TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'IDENTIFIED',
    IDENTIFIED_BY TEXT NOT NULL,
    IDENTIFIED_DATE TEXT NOT NULL,
    OWNER_ID TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RISK_REGISTER PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RISK_PROJECT ON pm_risk_register(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_PM_RISK_LEVEL ON pm_risk_register(RISK_LEVEL);

-- pm_risk_assessment 风险评估
CREATE TABLE IF NOT EXISTS pm_risk_assessment (
    ID TEXT NOT NULL,
    RISK_ID TEXT NOT NULL,
    ASSESSMENT_DATE TEXT NOT NULL,
    PROBABILITY INTEGER NOT NULL,
    IMPACT INTEGER NOT NULL,
    RISK_SCORE INTEGER NOT NULL,
    RISK_LEVEL TEXT NOT NULL,
    ASSESSMENT_NOTES TEXT,
    ASSESSED_BY TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RISK_ASSESSMENT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RA_RISK ON pm_risk_assessment(RISK_ID);

-- pm_risk_quantitative 风险定量分析
CREATE TABLE IF NOT EXISTS pm_risk_quantitative (
    ID TEXT NOT NULL,
    RISK_ID TEXT NOT NULL,
    ANALYSIS_METHOD TEXT NOT NULL,
    COST_IMPACT_MIN TEXT,
    COST_IMPACT_MAX TEXT,
    COST_IMPACT_EXPECTED TEXT,
    SCHEDULE_IMPACT_DAYS TEXT,
    EMV TEXT,
    TORNADO_DATA TEXT,
    ANALYSIS_NOTES TEXT,
    ANALYZED_BY TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RISK_QUANT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RQ_RISK ON pm_risk_quantitative(RISK_ID);

-- pm_risk_response 风险应对
CREATE TABLE IF NOT EXISTS pm_risk_response (
    ID TEXT NOT NULL,
    RISK_ID TEXT NOT NULL,
    STRATEGY TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    ACTION_ITEMS TEXT,
    OWNER_ID TEXT NOT NULL,
    DUE_DATE TEXT,
    COST_ESTIMATE TEXT,
    STATUS TEXT NOT NULL DEFAULT 'PLANNED',
    RESIDUAL_PROBABILITY INTEGER,
    RESIDUAL_IMPACT INTEGER,
    RESIDUAL_SCORE INTEGER,
    RESULT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RISK_RESPONSE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_RR_RISK ON pm_risk_response(RISK_ID);

-- pm_risk_monitor 风险监控
CREATE TABLE IF NOT EXISTS pm_risk_monitor (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    RISK_ID TEXT NOT NULL,
    MONITOR_DATE TEXT NOT NULL,
    CURRENT_STATUS TEXT NOT NULL,
    STATUS_TREND TEXT,
    NEW_TRIGGERS TEXT,
    NOTES TEXT,
    MONITORED_BY TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_RISK_MONITOR PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_RM_RMON_PROJECT ON pm_risk_monitor(PROJECT_ID);
