-- Procurement Management Tables (FR-PM-043 ~ FR-PM-045)

-- pm_vendor 供应商
CREATE TABLE IF NOT EXISTS pm_vendor (
    ID TEXT NOT NULL,
    VENDOR_CODE TEXT NOT NULL UNIQUE,
    NAME TEXT NOT NULL,
    CONTACT_PERSON TEXT,
    CONTACT_EMAIL TEXT,
    CONTACT_PHONE TEXT,
    CATEGORY TEXT,
    RATING TEXT,
    NOTES TEXT,
    STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_VENDOR PRIMARY KEY (ID)
);

-- pm_procurement_order 采购订单
CREATE TABLE IF NOT EXISTS pm_procurement_order (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ORDER_CODE TEXT NOT NULL UNIQUE,
    VENDOR_ID TEXT NOT NULL,
    ITEM_DESCRIPTION TEXT NOT NULL,
    QUANTITY TEXT NOT NULL,
    UNIT_PRICE TEXT NOT NULL,
    TOTAL_AMOUNT TEXT NOT NULL,
    CONTRACT_TYPE TEXT NOT NULL,
    ORDER_DATE TEXT NOT NULL,
    EXPECTED_DELIVERY_DATE TEXT,
    ACTUAL_DELIVERY_DATE TEXT,
    STATUS TEXT NOT NULL DEFAULT 'PENDING',
    ACCEPTANCE_CRITERIA TEXT,
    ACCEPTANCE_DATE TEXT,
    ACCEPTANCE_COMMENT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_PROCUREMENT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_PO_PROJECT ON pm_procurement_order(PROJECT_ID);

-- pm_procurement_variance 采购偏差
CREATE TABLE IF NOT EXISTS pm_procurement_variance (
    ID TEXT NOT NULL,
    ORDER_ID TEXT NOT NULL,
    VARIANCE_TYPE TEXT NOT NULL,
    PLANNED_VALUE TEXT,
    ACTUAL_VALUE TEXT,
    VARIANCE_AMOUNT TEXT,
    DESCRIPTION TEXT,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    DETECTED_DATE TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_PROC_VAR PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_PV_ORDER ON pm_procurement_variance(ORDER_ID);

-- pm_procurement_closure 采购收尾
CREATE TABLE IF NOT EXISTS pm_procurement_closure (
    ID TEXT NOT NULL,
    ORDER_ID TEXT NOT NULL,
    CLOSURE_TYPE TEXT NOT NULL,
    FINAL_SETTLEMENT TEXT,
    LESSONS_LEARNED TEXT,
    CLOSURE_DATE TEXT NOT NULL,
    CLOSURE_COMMENT TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_PROC_CLOSURE PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_PC_ORDER ON pm_procurement_closure(ORDER_ID);
