-- Stakeholder Management Tables (FR-PM-046 ~ FR-PM-049)

-- pm_stakeholder 干系人
CREATE TABLE IF NOT EXISTS pm_stakeholder (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    STAKEHOLDER_CODE TEXT NOT NULL UNIQUE,
    NAME TEXT NOT NULL,
    ORGANIZATION TEXT,
    ROLE TEXT NOT NULL,
    POWER_LEVEL TEXT NOT NULL,
    INTEREST_LEVEL TEXT NOT NULL,
    QUADRANT TEXT NOT NULL,
    CURRENT_ENGAGEMENT TEXT NOT NULL,
    DESIRED_ENGAGEMENT TEXT NOT NULL,
    ENGAGEMENT_GAP TEXT,
    INFLUENCE_SCORE INTEGER,
    EXPECTATIONS TEXT,
    NOTES TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_STAKEHOLDER PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SH_PROJECT ON pm_stakeholder(PROJECT_ID);

-- pm_stakeholder_engagement_plan 干系人参与计划
CREATE TABLE IF NOT EXISTS pm_stakeholder_engagement_plan (
    ID TEXT NOT NULL,
    STAKEHOLDER_ID TEXT NOT NULL,
    STRATEGY TEXT NOT NULL,
    ACTION_ITEMS TEXT,
    COMMUNICATION_FREQUENCY TEXT,
    COMMUNICATION_METHOD TEXT,
    SUCCESS_CRITERIA TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SH_ENG_PLAN PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SEP_SH ON pm_stakeholder_engagement_plan(STAKEHOLDER_ID);

-- pm_stakeholder_interaction 干系人互动
CREATE TABLE IF NOT EXISTS pm_stakeholder_interaction (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    STAKEHOLDER_ID TEXT NOT NULL,
    INTERACTION_TYPE TEXT NOT NULL,
    INTERACTION_DATE TEXT NOT NULL,
    SUMMARY TEXT NOT NULL,
    OUTCOME TEXT,
    ENGAGEMENT_SHIFT TEXT,
    FOLLOW_UP_ACTIONS TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SH_INTERACTION PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SI_PROJECT ON pm_stakeholder_interaction(PROJECT_ID);

-- pm_stakeholder_satisfaction 干系人满意度
CREATE TABLE IF NOT EXISTS pm_stakeholder_satisfaction (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    EVALUATION_PERIOD TEXT NOT NULL,
    STAKEHOLDER_ID TEXT,
    DIMENSIONS TEXT NOT NULL,
    OVERALL_SCORE TEXT,
    FEEDBACK TEXT,
    IMPROVEMENT_ACTIONS TEXT,
    EVALUATED_BY TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_SH_SAT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_SS_PROJECT ON pm_stakeholder_satisfaction(PROJECT_ID);
