-- Audit Log Table (Global)

-- pm_audit_log 审计日志
CREATE TABLE IF NOT EXISTS pm_audit_log (
    ID TEXT NOT NULL,
    PROJECT_ID TEXT NOT NULL,
    ENTITY_TYPE TEXT NOT NULL,
    ENTITY_ID TEXT NOT NULL,
    ACTION TEXT NOT NULL,
    OLD_VALUES TEXT,
    NEW_VALUES TEXT,
    PERFORMED_BY TEXT NOT NULL,
    PERFORMED_AT TEXT DEFAULT (datetime('now', 'localtime')),
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_PM_AUDIT_LOG PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_AL_PROJECT ON pm_audit_log(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_PM_AL_ENTITY ON pm_audit_log(ENTITY_TYPE, ENTITY_ID);
