-- WBS Management DDL (FR-PM-010)
-- Product and Module master data tables

-- erp_product 产品主数据
CREATE TABLE IF NOT EXISTS erp_product (
    ID TEXT NOT NULL,
    PRODUCT_CODE TEXT NOT NULL UNIQUE,
    PRODUCT_NAME TEXT NOT NULL,
    STATUS TEXT NOT NULL DEFAULT 'ACTIVE',
    DESCRIPTION TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_ERP_PRODUCT PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_ERP_PROD_CODE ON erp_product(PRODUCT_CODE);

-- erp_module 产品模块
CREATE TABLE IF NOT EXISTS erp_module (
    ID TEXT NOT NULL,
    PRODUCT_ID TEXT NOT NULL,
    MODULE_CODE TEXT NOT NULL,
    MODULE_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_ERP_MODULE PRIMARY KEY (ID),
    CONSTRAINT FK_ERP_MOD_PROD FOREIGN KEY (PRODUCT_ID) REFERENCES erp_product(ID)
);

CREATE INDEX IF NOT EXISTS IDX_ERP_MOD_PRODUCT ON erp_module(PRODUCT_ID);
