-- WBS Version History and pm_wbs_element extension (FR-PM-010)

-- pm_wbs_version WBS版本历史
CREATE TABLE IF NOT EXISTS pm_wbs_version (
    ID TEXT NOT NULL,
    WBS_ID TEXT NOT NULL,
    VERSION_NUMBER REAL NOT NULL,
    PLANNED_START_DATE TEXT,
    PLANNED_END_DATE TEXT,
    ACTUAL_START_DATE TEXT,
    ACTUAL_END_DATE TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    CONSTRAINT PK_PM_WBS_VERSION PRIMARY KEY (ID),
    CONSTRAINT FK_PM_WBS_VER_WBS FOREIGN KEY (WBS_ID) REFERENCES pm_wbs_element(ID)
);

CREATE INDEX IF NOT EXISTS IDX_PM_WBS_VER_WBS ON pm_wbs_version(WBS_ID);

-- ALTER TABLE pm_wbs_element 扩展新字段
ALTER TABLE pm_wbs_element ADD COLUMN PRODUCT_ID TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN MODULE_ID TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN PRIORITY TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN TECH_DIFFICULTY TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN PLANNED_OWNER_ID TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN LATEST_PLANNED_END_DATE TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN ACTUAL_END_DATE TEXT;
ALTER TABLE pm_wbs_element ADD COLUMN ACTUAL_COMPLETED_BY TEXT;

-- ALTER TABLE pm_wbs_version 添加 BaseEntity 审计字段
ALTER TABLE pm_wbs_version ADD COLUMN UPDATE_BY TEXT;
ALTER TABLE pm_wbs_version ADD COLUMN UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime'));
ALTER TABLE pm_wbs_version ADD COLUMN REMARKS TEXT;
ALTER TABLE pm_wbs_version ADD COLUMN DEL_FLAG TEXT DEFAULT '0';
ALTER TABLE pm_wbs_version ADD COLUMN VER_NO INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE pm_wbs_version ADD COLUMN SYS_CODE TEXT;
