-- Seed BUDGET sequence
INSERT INTO wh_sequence (SEQ_NAME, SEQ_VALUE, SEQ_PREFIX, SEQ_YEAR)
SELECT 'PM_BUDGET', 0, 'BUDGET-', 2026
WHERE NOT EXISTS (SELECT 1 FROM wh_sequence WHERE SEQ_NAME = 'PM_BUDGET');
