-- Work Hours & Work Calendar DDL (FR-PM-WORK-HOURS)

-- wh_sys_work_calendar 系统工作日历
CREATE TABLE IF NOT EXISTS wh_sys_work_calendar (
    ID TEXT NOT NULL,
    CALENDAR_DATE TEXT NOT NULL,
    DAY_TYPE TEXT NOT NULL,
    HOLIDAY_NAME TEXT,
    STANDARD_HOURS TEXT NOT NULL DEFAULT '8',
    YEAR TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_SYS_WORK_CALENDAR PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_WS_WC_DATE ON wh_sys_work_calendar(CALENDAR_DATE);
CREATE INDEX IF NOT EXISTS IDX_WS_WC_YEAR ON wh_sys_work_calendar(YEAR);

-- 工时查询索引
CREATE INDEX IF NOT EXISTS IDX_PM_WORKLOG_USER_DATE
    ON pm_work_log(CREATE_BY, LOG_DATE, STATUS);

CREATE INDEX IF NOT EXISTS IDX_PM_WORKLOG_PROJECT_DATE
    ON pm_work_log(PROJECT_ID, LOG_DATE);
