-- Deliverable Management Table
CREATE TABLE IF NOT EXISTS wh_pm_deliverable (
    ID TEXT NOT NULL,
    DELIVERABLE_CODE TEXT NOT NULL UNIQUE,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    PLANNED_DELIVERY_DATE TEXT,
    ACTUAL_DELIVERY_DATE TEXT,
    STATUS TEXT NOT NULL DEFAULT 'DRAFT',
    ATTACHMENTS TEXT,
    APPROVAL_COMMENT TEXT,
    PROCESS_INSTANCE_ID TEXT,
    PROJECT_ID TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_PM_DELIVERABLE PRIMARY KEY (ID),
    CONSTRAINT CK_WH_PM_DELIVERABLE_STATUS CHECK (STATUS IN (
        'DRAFT','PENDING_APPROVAL','APPROVED','DELIVERED','REJECTED'
    )),
    CONSTRAINT FK_WH_PM_DELIVERABLE_PROJECT FOREIGN KEY (PROJECT_ID)
        REFERENCES wh_pm_project_charter(ID)
);

CREATE INDEX IF NOT EXISTS IDX_WH_PM_DELIVERABLE_STATUS ON wh_pm_deliverable(STATUS);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_DELIVERABLE_PROJECT ON wh_pm_deliverable(PROJECT_ID);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_DELIVERABLE_CODE ON wh_pm_deliverable(DELIVERABLE_CODE);
CREATE INDEX IF NOT EXISTS IDX_WH_PM_DELIVERABLE_DEL ON wh_pm_deliverable(DEL_FLAG);

-- Seed PM_DELIVERABLE sequence
INSERT INTO wh_sequence (SEQ_NAME, SEQ_VALUE, SEQ_PREFIX, SEQ_YEAR)
SELECT 'PM_DELIVERABLE', 0, 'DELIVERABLE-', 2026
WHERE NOT EXISTS (SELECT 1 FROM wh_sequence WHERE SEQ_NAME = 'PM_DELIVERABLE');
