-- 交付成本定额管理 DDL

-- wh_sys_position 岗位表
CREATE TABLE IF NOT EXISTS wh_sys_position (
    ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    IS_DEFAULT TEXT NOT NULL DEFAULT '0',
    SORT_ORDER INTEGER DEFAULT 0,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_SYS_POSITION PRIMARY KEY (ID)
);

-- wh_sys_cost_year 成本年份表
CREATE TABLE IF NOT EXISTS wh_sys_cost_year (
    ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    START_DATE TEXT NOT NULL,
    END_DATE TEXT NOT NULL,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_SYS_COST_YEAR PRIMARY KEY (ID)
);

-- wh_sys_cost_quota 成本定额表
CREATE TABLE IF NOT EXISTS wh_sys_cost_quota (
    ID TEXT NOT NULL,
    POSITION_ID TEXT NOT NULL,
    YEAR_ID TEXT NOT NULL,
    VERSION_NO INTEGER NOT NULL DEFAULT 1,
    DAILY_RATE REAL NOT NULL,
    EFFECTIVE_DATE TEXT NOT NULL,
    CHANGE_REASON TEXT,
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_SYS_COST_QUOTA PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_WS_CQ_POSITION ON wh_sys_cost_quota(POSITION_ID);
CREATE INDEX IF NOT EXISTS IDX_WS_CQ_YEAR ON wh_sys_cost_quota(YEAR_ID);
CREATE INDEX IF NOT EXISTS IDX_WS_CQ_EFFECTIVE ON wh_sys_cost_quota(POSITION_ID, EFFECTIVE_DATE);

-- 插入默认9个岗位
INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-001', '管理', '1', 1, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-002', '职能', '1', 2, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-003', '架构', '1', 3, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-004', '售前', '1', 4, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-005', '产品', '1', 5, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-006', '开发', '1', 6, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-007', '质量', '1', 7, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-008', '实施', '1', 8, '0', 0);

INSERT OR IGNORE INTO wh_sys_position (ID, NAME, IS_DEFAULT, SORT_ORDER, DEL_FLAG, VER_NO)
VALUES ('pos-009', '项目管理', '1', 9, '0', 0);
