-- 字典表 DDL + 种子数据

-- wh_dict_type 字典类型表
CREATE TABLE IF NOT EXISTS wh_dict_type (
    ID TEXT NOT NULL,
    TYPE_CODE TEXT NOT NULL,
    TYPE_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    SORT_ORDER INTEGER DEFAULT 0,
    STATUS TEXT DEFAULT '1',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_DICT_TYPE PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_DICT_TYPE_CODE ON wh_dict_type(TYPE_CODE);

-- wh_dict_item 字典条目表
CREATE TABLE IF NOT EXISTS wh_dict_item (
    ID TEXT NOT NULL,
    TYPE_CODE TEXT NOT NULL,
    ITEM_CODE TEXT NOT NULL,
    ITEM_LABEL TEXT NOT NULL,
    ITEM_VALUE TEXT,
    TAG_TYPE TEXT,
    SORT_ORDER INTEGER DEFAULT 0,
    STATUS TEXT DEFAULT '1',
    CREATE_BY TEXT,
    CREATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    UPDATE_BY TEXT,
    UPDATE_DATE TEXT DEFAULT (datetime('now', 'localtime')),
    REMARKS TEXT,
    DEL_FLAG TEXT DEFAULT '0',
    VER_NO INTEGER DEFAULT 0 NOT NULL,
    SYS_CODE TEXT,
    CONSTRAINT PK_WH_DICT_ITEM PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_DICT_ITEM_TYPE ON wh_dict_item(TYPE_CODE, STATUS);

-- 种子数据：字典类型（11 个）
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT001', 'CHARTER_STATUS',      '项目章程状态',   1, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT002', 'BUDGET_STATUS',       '预算状态',       2, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT003', 'DELIVERABLE_STATUS',  '交付物状态',     3, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT004', 'WBS_ELEMENT_STATUS',  'WBS 任务状态',   4, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT005', 'WBS_ELEMENT_TYPE',    'WBS 任务类型',   5, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT006', 'WORKLOG_STATUS',      '工时记录状态',   6, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT007', 'COST_WARNING_STATUS', '成本预警状态',   7, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT008', 'CALENDAR_DAY_TYPE',   '日历日类型',     8, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT009', 'PRODUCT_STATUS',      '产品状态',       9, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT010', 'MODULE_STATUS',       '模块状态',       10, '1');
INSERT INTO wh_dict_type (ID, TYPE_CODE, TYPE_NAME, SORT_ORDER, STATUS) VALUES ('DCT011', 'CHARTER_PROGRESS',    '项目进度',       11, '1');

-- 种子数据：字典条目

-- CHARTER_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI001', 'CHARTER_STATUS', 'DRAFT',            '草稿',   'info',    1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI002', 'CHARTER_STATUS', 'PENDING_APPROVAL', '审批中', 'warning', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI003', 'CHARTER_STATUS', 'APPROVED',         '已通过', 'success', 3, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI004', 'CHARTER_STATUS', 'REJECTED',         '已驳回', 'danger',  4, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI005', 'CHARTER_STATUS', 'CLOSED',           '已关闭', '',        5, '1');

-- BUDGET_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI010', 'BUDGET_STATUS', 'DRAFT',    '草稿',   'info',    1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI011', 'BUDGET_STATUS', 'PENDING',  '审批中', 'warning', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI012', 'BUDGET_STATUS', 'APPROVED', '已审批', 'success', 3, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI013', 'BUDGET_STATUS', 'REJECTED', '已驳回', 'danger',  4, '1');

-- DELIVERABLE_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI020', 'DELIVERABLE_STATUS', 'DRAFT',            '草稿',   'info',    1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI021', 'DELIVERABLE_STATUS', 'PENDING_APPROVAL', '审批中', 'warning', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI022', 'DELIVERABLE_STATUS', 'APPROVED',         '已通过', 'success', 3, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI023', 'DELIVERABLE_STATUS', 'REJECTED',         '已驳回', 'danger',  4, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI024', 'DELIVERABLE_STATUS', 'DELIVERED',        '已交付', 'success', 5, '1');

-- WBS_ELEMENT_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI030', 'WBS_ELEMENT_STATUS', 'NOT_STARTED',    '未开始', 'info',    1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI031', 'WBS_ELEMENT_STATUS', 'IN_DEVELOPMENT', '开发中', 'primary', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI032', 'WBS_ELEMENT_STATUS', 'TESTING',        '已提测', 'warning', 3, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI033', 'WBS_ELEMENT_STATUS', 'COMPLETED',      '已完成', 'success', 4, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI034', 'WBS_ELEMENT_STATUS', 'SUSPENDED',      '已暂停', 'warning', 5, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI035', 'WBS_ELEMENT_STATUS', 'CANCELLED',      '已取消', 'danger',  6, '1');

-- WBS_ELEMENT_TYPE
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI040', 'WBS_ELEMENT_TYPE', 'TASK', '任务', '', 1, '1');

-- WORKLOG_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI050', 'WORKLOG_STATUS', 'DRAFT',    '待审批', 'info',    1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI051', 'WORKLOG_STATUS', 'APPROVED', '已通过', 'success', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI052', 'WORKLOG_STATUS', 'REJECTED', '已驳回', 'danger',  3, '1');

-- COST_WARNING_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI060', 'COST_WARNING_STATUS', 'ACTIVE', '活跃', 'warning', 1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI061', 'COST_WARNING_STATUS', 'CLOSED', '已关闭', '',      2, '1');

-- CALENDAR_DAY_TYPE
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI070', 'CALENDAR_DAY_TYPE', 'WORKDAY', '工作日', '',         1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI071', 'CALENDAR_DAY_TYPE', 'WEEKEND', '周末',   'info',    2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI072', 'CALENDAR_DAY_TYPE', 'HOLIDAY', '节假日', 'warning', 3, '1');

-- PRODUCT_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI080', 'PRODUCT_STATUS', 'ACTIVE',      '启用',     'success', 1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI081', 'PRODUCT_STATUS', 'INACTIVE',    '停用',     'info',    2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI082', 'PRODUCT_STATUS', 'PLACEHOLDER', '占位产品', 'warning', 3, '1');

-- MODULE_STATUS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI090', 'MODULE_STATUS', 'ACTIVE',   '启用', 'success', 1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI091', 'MODULE_STATUS', 'INACTIVE', '停用', 'info',    2, '1');

-- CHARTER_PROGRESS
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI100', 'CHARTER_PROGRESS', 'IN_PROGRESS', '进行中', 'primary', 1, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI101', 'CHARTER_PROGRESS', 'ACCEPTED',    '已验收', 'success', 2, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI102', 'CHARTER_PROGRESS', 'COMPLETED',   '已完成', 'success', 3, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI103', 'CHARTER_PROGRESS', 'SUSPENDED',   '已暂停', 'warning', 4, '1');
INSERT INTO wh_dict_item (ID, TYPE_CODE, ITEM_CODE, ITEM_LABEL, TAG_TYPE, SORT_ORDER, STATUS) VALUES ('DCI104', 'CHARTER_PROGRESS', 'CANCELLED',   '已取消', 'danger',  5, '1');
